### ISSUE TITLE
[BUG} Plugin does not function with Homebridge 1.3.1

### ISSUE THREAD

**Issue by produdegr** [lukasroegner/homebridge-nuki#73]
The plugin does not open/close Nuki doors with homebridge 1.3.1. 
When using the Homebridge UI in interactive mode, nothing happens.
When using Homekit app the doors remains as "Unlocking...", while in the homebridge log, no logs are shown.
If I unlock/lock the door with the nuki app, then the callback works just fine and all callbacks apear in the log.
So from Homebridge (and Homekit app because of that) the door open/close is not working.
Tried multiple times to reset Nuki bridge and restart Homebridge, but problem remains.

PS. clearly the autocorrecting feature of "illegal" values in homebridge 1.3.1 is to blame I think.

**Comment by redeemer666** [comment]
Hi Produde, may I ask if the issue appears only when using Siri, like issue #71, or happens also when trying to lock-unlock via the home app? I haven’t updated to 1.3.1 yet.

Thanks

**Comment by produdegr** [comment]
No, it happens with any command sequence, because it does not function when using Homebridge UI. So siri -> Homekit -> Homebridge -> Plugin won't work either.
I do not remember if it was ok with Homebridge 1.3.0, I suppose it was. So staying on Homebridge 1.3.0 (or 1.2.5) is recommended if you need it to function.

**Comment by Marfre888** [comment]
Weird,

In my case Siri has stopped working at all, however, the plugin still functions correctly, albeit a bit slower than before 1.3.0

Hoping @lukasroegner can take a look a this, as this plugin is superior to the other plugins on offer for nuki

**Comment by Marfre888** [comment]
@produdegr Are you using this nuki plugin as a child bridge?

**Comment by produdegr** [comment]
@Marfre888 No, I use it in the main homebridge thread. I can also report that sometimes opening a door did indeed work. This is weird because when testing the doors would not open or close from homekit. My setup is 2 Nuki Locks + Nuki Bridge.

**Comment by redeemer666** [comment]
The "slowliness" of the lock-unlock sequence is an issue that began with 1.3.0, if you use the plugin as a child bridge. For sure it's something connected with the changes they made with the latest version.

As with 1.3.1, I will not update it until it hear something from Lukas. My Setup is 2 Bridges and 2 Nuki Locks + 1 Opener. Two child bridges and you don't need anymore two separate instances of homebridge to make it work (that is very nice).

**Comment by Marfre888** [comment]
> The "slowliness" of the lock-unlock sequence is an issue that began with 1.3.0, if you use the plugin as a child bridge. For sure it's something connected with the changes they made with the latest version.
> 
> As with 1.3.1, I will not update it until it hear something from Lukas. My Setup is 2 Bridges and 2 Nuki Locks + 1 Opener. Two child bridges and you don't need anymore two separate instances of homebridge to make it work (that is very nice).

I’m on 3.0.1 and it’s working exactly the same for me.

It seems Lukas has decided to not continue to maintain this plugin

**Comment by redeemer666** [comment]
> It seems Lukas has decided to not continue to maintain this plugin

You Sure about this or it is only a guess of yours?

**Comment by Marfre888** [comment]
> > It seems Lukas has decided to not continue to maintain this plugin
> 
> You Sure about this or it is only a guess of yours?

An educated guess.. he hasn't been active here at all in the past couple of months, and he's updated a lot of other plugins in the meantime. 

Would love to get confirmation if it is the case though

**Comment by redeemer666** [comment]
> > > It seems Lukas has decided to not continue to maintain this plugin
> > 
> > 
> > You Sure about this or it is only a guess of yours?
> 
> An educated guess.. he hasn't been active here at all in the past couple of months, and he's updated a lot of other plugins in the meantime.
> 
> Would love to get confirmation if it is the case though

Really hope so, it’s the best one I’ve tried for controlling Nuki Devices…

**Comment by Marfre888** [comment]
Yeah, it is the best one, in terms of ease of setup, features, and Siri functionality

**Comment by produdegr** [comment]
After further testing, just to clarify: Lock/Unlock works from Home App. It does, however, not work if you Lock/Unlock from the Homebridge UI (homebridge -I) in homebridge interactive mode. You press the button but nothing happens and no "Lock" or "Unlock" command shows up in the UI log. With Siri, I get mixed results and think that is sometimes works, but rarely.

**Comment by crouchingtiger** [comment]
I believe the same issue is affecting the other nuki plugin. See https://github.com/ebaauw/homebridge-nb/issues/26

I believe Homebridge is sending the plugins (or any device that registers with the https://developers.homebridge.io/#/service/LockMechanism the wrong data type).

**Comment by crouchingtiger** [comment]
Issue is resolved in Homebridge. Update to 1.3.3 beta and it should probably work for this plugin also.

**Comment by Marfre888** [comment]
@crouchingtiger Ok, so I updated to 1.3.3beta and can confirm that Siri does work correctly now.. However, I’ve noticed that now it doesn’t acknowledge if the lock has been opened, when before 1.3.0 it did.

Is that related to the Homebridge?

**Comment by redeemer666** [comment]
I'm with 1.3.2 and Siri issue persist. Waiting for 1.3.3 to came out of Beta though, don't want to destroy my home if some incompatibilities appears with other plugins.

@Marfre888 I think this is something related to Siri and timeout time. It happens most of the time to me also, becasue the connection is not very "fast". Maybe 1.3.0 slowed down a little bit the status report of the devices, and this cause the issue (I've the same with other plugins, like the Fibaro one from ilcato).

**Comment by Marfre888** [comment]
> I'm with 1.3.2 and Siri issue persist. Waiting for 1.3.3 to came out of Beta though, don't want to destroy my home if some incompatibilities appears with other plugins.
> 
> @Marfre888 I think this is something related to Siri and timeout time. It happens most of the time to me also, becasue the connection is not very "fast". Maybe 1.3.0 slowed down a little bit the status report of the devices, and this cause the issue (I've the same with other plugins, like the Fibaro one from ilcato).

Updating to the beta can't break anything at this point, but it does it, just roll it back to 1.3.2 through the config ui.. works great

No, with timeout, Siri says, some devices did not respond.. now she just says Ok.. but never acknowledges that it opened it

**Comment by crouchingtiger** [comment]
@Marfre888 I can't really say where your other issue might be, I didn't sift through the boolean checks in this plugin's source so much, as I personally use https://github.com/ebaauw/homebridge-nb and that's working fine with both my Nuki Opener and Nuki Smart Lock.

**Comment by Marfre888** [comment]
@crouchingtiger Tbh I prefer it as it is now, as before it worked 4 out of 5 times.

Does Siri acknowledge when the lock is opened for you?

I’ll try running the debug and report back.

**Comment by Marfre888** [comment]
@crouchingtiger, I've rolled back to 1.2.5, and it behaves the same way.. it seems Apple has changed the way Siri behaves when unlocking a door. Now she just says 'Ok', or 'Done' if successful and says 'She shouldn't do that' if the instruction has failed. While a couple of weeks ago, she used to say, 'unlocking door', followed by 'door unlocked' when successful.

I've attached below the log from '`DEBUG=HAP-NodeJS:Accessory`, it seems to be working correctly now.

Homebrdige Firmware 1.2.5

![Inked1 2 5 wif1](https://user-images.githubusercontent.com/63603736/110346411-ce6cff00-802f-11eb-9a6a-09dee7b353e8.jpg)

Homebridge Firmware 1.3.3 Beta 6

![Inked1 3 3 wifi](https://user-images.githubusercontent.com/63603736/110346425-d2991c80-802f-11eb-865a-ab687838c74a.jpg)

**Comment by produdegr** [comment]
Tested to be OK with final version of Homebridge 1.3.3.
Issue resolved.

**Comment by crouchingtiger** [comment]
@Marfre888 I have Siri voice feedback turned off so I'm not sure on previous / current behaviour to be honest.

Not sure if those commands were issued via Home or Siri, but you would have to have test on each Homebridge version if you see a difference in processing between HomeKit and Siri.

In any case, 1.3.3 contains the bug fix for my issue so Homebridge should handle false/0 handling inconsistencies much better. Some plugins still might need updating based on the 1.3.0 characteristic changes however.
